export const PRODUCT_ADD = "PRODUCT_ADD"
export const PRODUCT_UPDATE = "PRODUCT_UPDATE"
export const PRODUCT_REQUESTED = "PRODUCT_REQUESTED"
export const PRODUCT_RECEIVED = "PRODUCT_RECEIVED"
export const PRODUCT_EMIT = "PRODUCT_EMIT"

export const SOCKET_ROOM_REQUESTED = "SOCKET_ROOM_REQUESTED"
export const SOCKET_ROOM_JOINED = "SOCKET_ROOM_JOINED"
export const SOCKET_ROOM_LEFT = "SOCKET_ROOM_LEFT"

