export const PRODUCT_ADD = "PRODUCT_ADD"
export const PRODUCT_UPDATE = "PRODUCT_UPDATE"
export const PRODUCT_REQUESTED = "PRODUCT_REQUESTED"
export const PRODUCT_RECEIVED = "PRODUCT_RECEIVED"
export const PRODUCT_EMIT = "PRODUCT_EMIT"



