export const PRODUCT_ADD = "PRODUCT_ADD"
export const PRODUCT_UPDATE = "PRODUCT_UPDATE"
export const PRODUCT_REQUESTED = "PRODUCT_REQUESTED"
export const PRODUCT_RECEIVED = "PRODUCT_RECEIVED"
export const PRODUCT_EMIT = "PRODUCT_EMIT"

export const SOCKET_ROOM_JOIN_REQUESTED = "SOCKET_ROOM_JOIN_REQUESTED"
export const SOCKET_ROOM_LEAVE_REQUESTED = "SOCKET_ROOM_LEAVE_REQUESTED"
export const SOCKET_ROOM_CREATE_REQUESTED = "SOCKET_ROOM_CREATE_REQUESTED"

export const SOCKET_ROOM_JOINED = "SOCKET_ROOM_JOINED"
export const SOCKET_ROOM_LEFT = "SOCKET_ROOM_LEFT"
export const SOCKET_ROOM_CREATED = "SOCKET_ROOM_CREATED"

